<?php
return array(
    // 반찬류

    // 간장 볶음
    '간장멸치견과류볶음' => array( // 110g 2019-09-30
        '_total' => array(100, 'g', false, ''),
        '_expired' => array(7, 'days', false, ''),
        '_regular' => array(2, 3700, 1), // 가중치, 가격, 분류(1:야채X)

        '멸치' => array(40, 'g', true, '국산'),
        '설탕' => array(2, 'g', false, '국산'),
        '모듬견과류' => array(35, 'g', true, ''),
        '간장볶음소스' => array(30, 'g', false, ''),
        '물엿' => array(12, 'g', false, '국산'),
        '깨' => array(1, 'g', false, '국산'),
        '참기름' => array(1, 'g', false, '국산'),
    ),
    '간장멸치볶음' => array( // 110g 2019-10-17
        '_total' => array(100, 'g', false, ''),
        '_expired' => array(7, 'days', false, ''),
        '_regular' => array(2, 3700, 1),

        '멸치' => array(60, 'g', true, '국산'),
        '설탕' => array(2, 'g', false, '국산'),
        '간장볶음소스' => array(45, 'g', false, ''),
        '물엿' => array(12, 'g', false, '국산'),
        '깨' => array(1, 'g', false, '국산'),
        '참기름' => array(1, 'g', false, '국산'),
    ),
    '간장명엽채볶음' => array(
        '_total' => array(110, 'g', false, ''),
        '_expired' => array(7, 'days', false, ''),
        '_regular' => array(2, 3200, 1),

        '명엽채' => array(80, 'g', true, '칠레'),
        '설탕' => array(2, 'g', false, '국산'),
        '맛기름' => array(5, 'g', false, '국산'),
        '간장볶음소스' => array(25, 'g', false, ''),
        '깨' => array(1, 'g', false, '국산'),
        '물엿' => array(12, 'g', false, '국산'),
        '참기름' => array(1, 'g', false, '국산'),
    ),
    '간장어묵볶음' => array( // 210g 2019-10-17
        '_total' => array(200, 'g', false, ''),
        '_expired' => array(7, 'days', false, ''),
        '_regular' => array(2, 2700, 1),

        '어묵' => array(120, 'g', true, '국산'),
        '설탕' => array(2, 'g', false, '국산'),
        '맛기름' => array(5, 'g', false, '국산'),
        '모듬야채' => array(30, 'g', true, '국산'),
        '간장볶음소스' => array(50, 'g', false, ''),
        '깨' => array(1, 'g', false, '국산'),
        '물엿' => array(5, 'g', false, '국산'),
        '참기름' => array(1, 'g', false, '국산'),
    ),
    '간장가지볶음' => array( // 170g 2019-09-30
        '_total' => array(150, 'g', false, ''),
        '_expired' => array(4, 'days', false, ''),
        '_regular' => array(2, 3700, 2),

        '가지' => array(170, 'g', true, '국산'),
        '소금' => array(2, 'g', false, '국산'),
        '모듬야채' => array(25, 'g', true, '국산'),
        '맛기름' => array(2, 'g', false, '국산'),
        '들기름' => array(2, 'g', false, '국산'),
        '간장볶음소스' => array(12, 'g', false, ''),
        '무침소스' => array(4, 'g', false, ''),
        '깨' => array(1, 'g', false, '국산'),
        '참기름' => array(1, 'g', false, '국산'),
    ),
    '간장새송이버섯볶음' => array(
        '_total' => array(150, 'g', false, ''),
        '_expired' => array(4, 'days', false, ''),
        '_regular' => array(2, 3200, 2),

        '새송이버섯' => array(200, 'g', true, '국산'),
        '모듬야채' => array(50, 'g', true, '국산'),
        '맛기름' => array(3, 'g', false, '국산'),
        '들기름' => array(3, 'g', false, '국산'),
        '간장볶음소스' => array(15, 'g', false, ''),
        '무침소스' => array(8, 'g', false, ''),
        '깨' => array(1, 'g', false, '국산'),
        '참기름' => array(1, 'g', false, '국산'),
    ),
    '간장느타리버섯볶음' => array( // 170g 2019-09-29
        '_total' => array(150, 'g', false, ''),
        '_expired' => array(4, 'days', false, ''),
        '_regular' => array(2, 3700, 2),

        '느타리버섯' => array(240, 'g', true, '국산'),
        '모듬야채' => array(40, 'g', true, '국산'),
        '맛기름' => array(2, 'g', false, '국산'),
        '들기름' => array(2, 'g', false, '국산'),
        '간장볶음소스' => array(12, 'g', false, ''),
        '무침소스' => array(7, 'g', false, ''),
        '깨' => array(1, 'g', false, '국산'),
        '참기름' => array(1, 'g', false, '국산'),
    ),
    '간장고사리볶음' => array( // 2019-09-29
        '_total' => array(150, 'g', false, ''),
        '_expired' => array(7, 'days', false, ''),
        '_regular' => array(2, 3200, 2),

        '고사리' => array(200, 'g', true, '중국'),
        '맛기름' => array(6, 'g', false, '국산'),
        '들기름' => array(17, 'g', false, '국산'),
        '모듬야채' => array(20, 'g', true, '국산'),
        '국간장' => array(10, 'g', false, '국산'),
        '간장볶음소스' => array(15, 'g', false, ''),
        '무침소스' => array(4, 'g', false, ''),
        '다시육수' => array(15, 'g', true, '국산'),
        '깨' => array(1, 'g', false, '국산'),
        '참기름' => array(1, 'g', false, '국산'),
    ),
    '간장미역줄기볶음' => array( // 160g 2019-10-09
        '_total' => array(150, 'g', false, ''),
        '_expired' => array(7, 'days', false, ''),
        '_regular' => array(2, 3200, 2),

        '미역줄기' => array(200, 'g', true, '국산'),
        '맛기름' => array(3, 'g', false, '국산'),
        '들기름' => array(3, 'g', false, '국산'),
        '모듬야채' => array(30, 'g', true, '국산'),
        '간장볶음소스' => array(20, 'g', false, ''),
        '무침소스' => array(5, 'g', false, ''),
        '다시육수' => array(10, 'g', true, '국산'),
        '깨' => array(1, 'g', false, '국산'),
        '참기름' => array(1, 'g', false, '국산'),
    ),
    '간장오징어실채볶음' => array( // 85g 2019-10-03
        '_total' => array(80, 'g', false, ''),
        '_expired' => array(7, 'days', false, ''),
        '_regular' => array(2, 4200, 1),

        '오징어실채' => array(55, 'g', true, '페루'),
        '설탕' => array(2, 'g', false, '국산'),
        '맛기름' => array(2, 'g', false, '국산'),
        '간장볶음소스' => array(22, 'g', false, ''),
        '깨' => array(1, 'g', false, '국산'),
        '참기름' => array(1, 'g', false, '국산'),
    ),
    '감자베이컨볶음' => array( // 150 2019-10-21
        '_total' => array(150, 'g', false, ''),
        '_expired' => array(7, 'days', false, ''),
        '_regular' => array(1, 3700, 1),

        '감자' => array(150, 'g', true, '국산'),
        '베이컨' => array(30, 'g', true, '미국'),
        '간장볶음소스' => array(40, 'g', false, ''),
        '깨' => array(1, 'g', false, '국산'),
    ),
    '마늘쫑베이컨볶음' => array( // 180 2019-10-21
        '_total' => array(180, 'g', false, ''),
        '_expired' => array(7, 'days', false, ''),
        '_regular' => array(2, 4200, 1),

        '마늘쫑' => array(150, 'g', true, '중국'),
        '베이컨' => array(30, 'g', true, '수입'),
        '간장볶음소스' => array(40, 'g', false, ''),
        '깨' => array(1, 'g', false, '국산'),
    ),

    // 고추장 볶음
    '매콤멸치견과류볶음' => array( // 110g 2019-09-30
        '_total' => array(100, 'g', false, ''),
        '_expired' => array(7, 'days', false, ''),
        '_regular' => array(2, 3700, 1),

        '멸치' => array(40, 'g', true, '국산'),
        '설탕' => array(2, 'g', false, '국산'),
        '모듬견과류' => array(35, 'g', true, ''),
        '고추장볶음소스' => array(30, 'g', false, ''),
        '물엿' => array(10, 'g', false, '국산'),
        '깨' => array(1, 'g', false, '국산'),
        '참기름' => array(1, 'g', false, '국산'),
    ),
    '매콤멸치볶음' => array( // 110g 2019-10-17
        '_total' => array(100, 'g', false, ''),
        '_expired' => array(7, 'days', false, ''),
        '_regular' => array(2, 3700, 1),

        '멸치' => array(60, 'g', true, '국산'),
        '설탕' => array(2, 'g', false, '국산'),
        '고추장볶음소스' => array(45, 'g', false, ''),
        '물엿' => array(10, 'g', false, '국산'),
        '깨' => array(1, 'g', false, '국산'),
        '참기름' => array(1, 'g', false, '국산'),
    ),
    '매콤건새우볶음' => array( // 100g 2019-10-09
        '_total' => array(100, 'g', false, ''),
        '_expired' => array(7, 'days', false, ''),
        '_regular' => array(2, 3700, 1),

        '건새우' => array(45, 'g', true, '중국'),
        '설탕' => array(2, 'g', false, '국산'),
        '고추장볶음소스' => array(45, 'g', false, ''),
        '물엿' => array(5, 'g', false, '국산'),
        '깨' => array(1, 'g', false, '국산'),
        '참기름' => array(1, 'g', false, '국산'),
    ),
    '매콤어묵볶음' => array( // 210g 2019-10-17
        '_total' => array(200, 'g', false, ''),
        '_expired' => array(7, 'days', false, ''),
        '_regular' => array(2, 2700, 1),

        '어묵' => array(120, 'g', true, '국산'),
        '설탕' => array(2, 'g', false, '국산'),
        '맛기름' => array(5, 'g', false, '국산'),
        '모듬야채' => array(30, 'g', true, '국산'),
        '고추장볶음소스' => array(60, 'g', false, ''),
        '물엿' => array(5, 'g', false, '국산'),
        '깨' => array(1, 'g', false, '국산'),
        '참기름' => array(1, 'g', false, '국산'),
    ),
    '매콤진미채무침' => array( // 120g 2019-09-30
        '_total' => array(100, 'g', false, ''),
        '_expired' => array(7, 'days', false, ''),
        '_regular' => array(2, 4200, 1),

        '진미채' => array(75, 'g', true, '페루'),
        '마요네즈' => array(8, 'g', false, '국산'),
        '고추장볶음소스' => array(40, 'g', false, ''),
        '깨' => array(1, 'g', false, '국산'),
        '참기름' => array(1, 'g', false, '국산'),
    ),
    '소세지야채볶음' => array(
        '_total' => array(150, 'g', false, ''),
        '_expired' => array(7, 'days', false, ''),
        '_regular' => array(2, 3700, 1),

        '비엔나소세지' => array(150, 'g', true, '국산'),
        '맛기름' => array(3, 'g', false, '국산'),
        '모듬야채' => array(50, 'g', true, '국산'),
        '고추장볶음소스' => array(20, 'g', false, ''),
        '케찹' => array(20, 'g', false, ''),
        '깨' => array(1, 'g', false, '국산'),
        '참기름' => array(1, 'g', false, '국산'),
    ),
    '마파두부' => array( // 250g 2019-10-21
        '_total' => array(250, 'g', false, ''),
        '_expired' => array(7, 'days', false, ''),
        '_regular' => array(2, 3700, 1),

        '두부' => array(150, 'g', true, '국산'),
        '고추기름' => array(4, 'g', false, '국산'),
        '돼지고기(다진)' => array(25, 'g', true, '국산'),
        '고추장볶음소스' => array(30, 'g', false, ''),
        '두반장' => array(10, 'g', false, '홍콩'),
        '굴소스' => array(5, 'g', false, '홍콩'),
        '다시육수' => array(50, 'g', true, '국산'),
        '감자전분' => array(2, 'g', false, '국산'),
    ),

    // 조림
    '우엉조림' => array( // 200g 2019-09-30
        '_total' => array(180, 'g', false, ''),
        '_expired' => array(7, 'days', false, ''),
        '_regular' => array(1, 3700, 1),

        '우엉' => array(240, 'g', true, '국내'),
        '간장조림소스' => array(150, 'g', false, ''),
        '식초' => array(2, 'g', false, '국산'),
        '맛기름' => array(3, 'g', false, '국산'),
        '물엿' => array(7, 'g', false, '국산'),
        '꿀' => array(5, 'g', false, '국산'),
        '깨' => array(1, 'g', false, '국산'),
        '참기름' => array(1, 'g', false, '국산'),
    ),
    '연근조림' => array( // 200g 2019-09-30
        '_total' => array(180, 'g', false, ''),
        '_expired' => array(7, 'days', false, ''),
        '_regular' => array(2, 3700, 1),

        '연근' => array(260, 'g', true, '국산'),
        '간장조림소스' => array(150, 'g', false, ''),
        '식초' => array(3, 'g', false, '국산'),
        '맛기름' => array(4, 'g', false, '국산'),
        '물엿' => array(11, 'g', false, '국산'),
        '꿀' => array(6, 'g', false, '국산'),
        '깨' => array(1, 'g', false, '국산'),
        '참기름' => array(1, 'g', false, '국산'),
    ),
    '땅콩조림' => array( // 200g 2019-09-30
        '_total' => array(180, 'g', false, ''),
        '_expired' => array(7, 'days', false, ''),
        '_regular' => array(2, 3700, 1),

        '생땅콩' => array(120, 'g', true, '중국'),
        '간장조림소스' => array(170, 'g', false, ''),
        '물엿' => array(10, 'g', false, '국산'),
        '깨' => array(1, 'g', false, '국산'),
        '참기름' => array(1, 'g', false, '국산'),
    ),
    '검은콩조림' => array( // 200g 2019-09-30
        '_total' => array(180, 'g', false, ''),
        '_expired' => array(7, 'days', false, ''),
        '_regular' => array(2, 4200, 1),

        '검은콩' => array(100, 'g', true, '국산'),
        '간장조림소스' => array(100, 'g', false, ''),
        '물엿' => array(14, 'g', false, '국산'),
        '깨' => array(1, 'g', false, '국산'),
        '참기름' => array(1, 'g', false, '국산'),
    ),
    '메추리알조림' => array( // 200g 2019-10-09
        '_total' => array(200, 'g', false, ''),
        '_expired' => array(4, 'days', false, ''),
        '_regular' => array(2, 3700, 1),

        '메추리알' => array(230, 'g', true, '국산'),
        '간장조림소스' => array(150, 'g', false, ''),
        '물엿' => array(12, 'g', false, '국산'),
        '깨' => array(1, 'g', false, '국산'),
        '참기름' => array(1, 'g', false, '국산'),
    ),
    '소불고기장조림' => array( // 200g 2020-01-31
        '_total' => array(180, 'g', false, ''),
        '_expired' => array(4, 'days', false, ''),

        '소고기' => array(90, 'g', true, '호주'),
        '메추리알' => array(120, 'g', true, '국산'),
        '간장조림소스' => array(110, 'g', false, ''),
        '대파' => array(4, 'g', false, '국산'),
        '생강술' => array(7, 'g', false, ''),
        '마늘' => array(7, 'g', false, '국산'),
        '양파' => array(12, 'g', false, '국산'),
        '물엿' => array(2, 'g', false, '국산'),
    ),
    '돼지고기장조림' => array( // 200g 2019-10-06
        '_total' => array(180, 'g', false, ''),
        '_expired' => array(4, 'days', false, ''),

        '돼지고기(장조림)' => array(70, 'g', true, '국산'),
        '메추리알' => array(120, 'g', true, '국산'),
        '간장조림소스' => array(110, 'g', false, ''),
        '꽈리고추' => array(15, 'g', true, '국산'),
        '양파' => array(8, 'g', false, '국산'),
        '마늘' => array(4, 'g', false, '국산'),
        '생강술' => array(4, 'g', false, ''),
        '물엿' => array(2, 'g', false, '국산'),
    ),
    '두부조림' => array( // 220g 2019-09-30
        '_total' => array(200, 'g', false, ''),
        '_expired' => array(4, 'days', false, ''),
        '_regular' => array(1, 3200, 1),

        '두부' => array(300, 'g', true, '국산'),
        '간장조림소스' => array(30, 'g', false, ''),
        '진간장' => array(12, 'g', false, '국산'),
        '깨' => array(1, 'g', false, '국산'),
        '참기름' => array(6, 'g', false, '국산'),
    ),
    '두부매콤조림' => array( // 220g 2019-09-30
        '_total' => array(200, 'g', false, ''),
        '_expired' => array(4, 'days', false, ''),
        '_regular' => array(1, 3200, 1),

        '두부' => array(230, 'g', true, '국산'),
        '간장조림소스' => array(23, 'g', false, ''),
        '고추장볶음소스' => array(46, 'g', false, ''),
        '진간장' => array(3, 'g', false, '국산'),
        '깨' => array(1, 'g', false, '국산'),
        '참기름' => array(1, 'g', false, '국산'),
    ),

    // 나물
    '콩나물무침' => array( // 200g 2019-10-10
        '_total' => array(200, 'g', false, ''),
        '_expired' => array(4, 'days', false, ''),
        '_regular' => array(2, 3200, 2),

        '콩나물' => array(200, 'g', true, '국산'),
        '모듬야채' => array(18, 'g', true, '국산'),
        '무침소스' => array(15, 'g', false, ''),
        '깨' => array(1, 'g', false, '국산'),
        '참기름' => array(1, 'g', false, '국산'),
    ),
    '숙주나물무침' => array( // 220g 2019-10-10
        '_total' => array(200, 'g', false, ''),
        '_expired' => array(4, 'days', false, ''),

        '숙주나물' => array(200, 'g', true, '국산'),
        '모듬야채' => array(12, 'g', true, '국산'),
        '무침소스' => array(15, 'g', false, ''),
        '깨' => array(1, 'g', false, '국산'),
        '참기름' => array(1, 'g', false, '국산'),
    ),
    '시금치무침' => array(
        '_total' => array(200, 'g', false, ''),
        '_expired' => array(4, 'days', false, ''),
        '_regular' => array(2, 3700, 2),

        '시금치' => array(200, 'g', true, '국산'),
        '무침소스' => array(10, 'g', false, ''),
        '깨' => array(1, 'g', false, '국산'),
        '참기름' => array(1, 'g', false, '국산'),
    ),
    '건파래무침' => array( // 160g 2019-10-09
        '_total' => array(150, 'g', false, ''),
        '_expired' => array(4, 'days', false, ''),
        '_regular' => array(2, 3700, 2),

        '건파래' => array(35, 'g', true, '국산'),
        '조림소스' => array(120, 'g', false, ''),
        '다시육수' => array(15, 'g', true, '국산'),
        '깨' => array(1, 'g', false, '국산'),
        '참기름' => array(2, 'g', false, '국산'),
    ),
    '새우젓애호박볶음' => array( // 170g 2019-10-09
        '_total' => array(150, 'g', false, ''),
        '_expired' => array(4, 'days', false, ''),
        '_regular' => array(2, 3200, 2),

        '애호박' => array(170, 'g', true, '국산'),
        '모듬야채' => array(20, 'g', true, '국산'),
        '맛기름' => array(1, 'g', false, '국산'),
        '들기름' => array(1, 'g', false, '국산'),
        '무침소스' => array(4, 'g', false, ''),
        '마늘' => array(3, 'g', false, '국산'),
        '새우젓' => array(3, 'g', false, '국산'),
        '깨' => array(1, 'g', false, '국산'),
        '참기름' => array(1, 'g', false, '국산'),
    ),
    '새우젓애호박복음' => array( // 170g 2019-10-09
        '_total' => array(150, 'g', false, ''),
        '_expired' => array(4, 'days', false, ''),
        '_regular' => array(2, 3200, 2),

        '애호박' => array(170, 'g', true, '국산'),
        '모듬야채' => array(20, 'g', true, '국산'),
        '맛기름' => array(1, 'g', false, '국산'),
        '들기름' => array(1, 'g', false, '국산'),
        '무침소스' => array(4, 'g', false, ''),
        '마늘' => array(3, 'g', false, '국산'),
        '새우젓' => array(3, 'g', false, '국산'),
        '깨' => array(1, 'g', false, '국산'),
        '참기름' => array(1, 'g', false, '국산'),
    ),
    '들깨무나물' => array( // 210g 2019-10-09
        '_total' => array(200, 'g', false, ''),
        '_expired' => array(4, 'days', false, ''),
        '_regular' => array(1, 2700, 2),

        '무' => array(230, 'g', true, '국산'),
        '무침소스' => array(11, 'g', false, ''),
        '들깨가루' => array(3, 'g', false, '중국'),
        '대파' => array(5, 'g', false, '국산'),
        '맛기름' => array(2, 'g', false, '국산'),
        '들기름' => array(2, 'g', false, '국산'),
        '마늘' => array(3, 'g', false, '국산'),
        '다시육수' => array(8, 'g', true, '국산'),
    ),
    '무나물' => array( // 220g 2019-09-30
        '_total' => array(200, 'g', false, ''),
        '_expired' => array(4, 'days', false, ''),
        '_regular' => array(1, 2700, 2),

        '무' => array(270, 'g', true, '국산'),
        '소금' => array(2, 'g', false, '국산'),
        '마늘' => array(3, 'g', false, '국산'),
        '들기름' => array(3, 'g', false, '국산'),
        '맛기름' => array(1, 'g', false, '국산'),
        '국간장' => array(4, 'g', false, '국산'),
        '다시육수' => array(11, 'g', true, '국산'),
    ),
    '무생채' => array( // 220g 2019-09-30
        '_total' => array(200, 'g', false, ''),
        '_expired' => array(7, 'days', false, ''),
        '_regular' => array(2, 2700, 2),

        '무' => array(220, 'g', true, '국산'),

        '앳젓' => array(9, 'g', false, '국산'),
        '매실청' => array(7, 'g', false, '국산'),
        '설탕' => array(3, 'g', false, '국산'),
        '소금' => array(1, 'g', false, '국산'),
        '마늘' => array(7, 'g', false, '국산'),
        '고춧가루' => array(5, 'g', false, '국산'),
        '대파' => array(9, 'g', false, '국산'),
    ),
    '새콤무생채' => array( // 220g 2019-10-03
        '_total' => array(200, 'g', false, ''),
        '_expired' => array(7, 'days', false, ''),
        '_regular' => array(2, 2700, 2),

        '무' => array(190, 'g', true, '국산'),
        '마늘' => array(6, 'g', false, '국산'),
        '매실청' => array(6, 'g', false, '국산'),
        '설탕' => array(8, 'g', false, '국산'),
        '식초' => array(10, 'g', false, '국산'),
        '고춧가루' => array(4, 'g', false, '국산'),
        '새우젓' => array(4, 'g', false, '국산'),
        '대파' => array(8, 'g', false, '국산'),
    ),
    '깻잎무침' => array( // 170g 2019-09-30
        '_total' => array(150, 'g', false, ''),
        '_expired' => array(7, 'days', false, ''),
        '_regular' => array(1, 3700, 2),

        '깻잎' => array(40, 'g', true, '국산'),
        '매실청' => array(10, 'g', false, '국산'),
        '고춧가루' => array(5, 'g', false, '국산'),
        '설탕' => array(1, 'g', false, '국산'),
        '맛간장' => array(23, 'g', false, '국산'),
        '멸치액젓' => array(10, 'g', false, '국산'),
        '마늘' => array(9, 'g', false, '국산'),
        '모듬야채' => array(45, 'g', true, '국산'),
    ),
    '오이부추무침' => array( // 2019-09-29
        '_total' => array(150, 'g', false, ''),
        '_expired' => array(7, 'days', false, ''),
        '_regular' => array(2, 3700, 2),

        '오이' => array(100, 'g', true, '국산'),
        '부추' => array(40, 'g', true, '국산'),
        '양파' => array(4, 'g', false, '국산'),
        '마늘' => array(3, 'g', false, '국산'),
        '매실청' => array(2, 'g', false, '국산'),
        '고춧가루' => array(3, 'g', false, '국산'),
        '설탕' => array(1, 'g', false, '국산'),
        '맛간장' => array(1, 'g', false, '국산'),
    ),
    '아삭이된장무침' => array( // 150g 2019-10-21
        '_total' => array(150, 'g', false, ''),
        '_expired' => array(7, 'days', false, ''),
        '_regular' => array(2, 3700, 2),

        '오이고추' => array(150, 'g', true, '국산'),
        '된장' => array(25, 'g', false, '국산'),
        '고추장' => array(10, 'g', false, '국산'),
        '들깨가루' => array(4, 'g', false, '중국'),
        '매실청' => array(5, 'g', false, '국산'),
        '설탕' => array(2, 'g', false, '국산'),
        '고춧가루' => array(3, 'g', false, '국산'),
        '마늘' => array(8, 'g', false, '국산'),
        '호박씨' => array(7, 'g', true, '중국'),
        '해바라기씨' => array(8, 'g', true, '중국'),
    ),
    '무말랭이무침' => array( // 2019-10-21
        '_total' => array(180, 'g', false, ''),
        '_expired' => array(7, 'days', false, ''),

        '무말랭이' => array(100, 'g', false, '중국'),
        '고춧잎' => array(30, 'g', false, '중국'),
        '참기름' => array(1, 'g', false, '국산'),
        '고추장볶음소스' => array(5, 'g', false, ''),
        'L-글루탐산나트륨' => array(1, 'g', false, '수입'),
        '멸치액젓' => array(1, 'g', false, '수입'),
    ),
    '더덕무침' => array( // 2019-10-21
        '_total' => array(200, 'g', false, ''),
        '_expired' => array(7, 'days', false, ''),

        '더덕' => array(100, 'g', false, '중국'),
        '참기름' => array(1, 'g', false, '국산'),
        '깨' => array(1, 'g', false, '국산'),
        '고추장볶음소스' => array(5, 'g', false, ''),
        'L-글루탐산나트륨' => array(1, 'g', false, '수입'),
    ),
    '고들빼기무침' => array( // 2019-10-21
        '_total' => array(200, 'g', false, ''),
        '_expired' => array(7, 'days', false, ''),

        '고들빼기' => array(100, 'g', false, '중국'),
        '참기름' => array(1, 'g', false, '국산'),
        '깨' => array(1, 'g', false, '국산'),
        '고추장볶음소스' => array(5, 'g', false, ''),
        '멸치액젓' => array(1, 'g', false, '수입'),
        'L-글루탐산나트륨' => array(1, 'g', false, '수입'),
    ),
    '깻잎장아찌' => array( // 2019-10-21
        '_total' => array(200, 'g', false, ''),
        '_expired' => array(7, 'days', false, ''),

        '깻잎' => array(100, 'g', false, '중국'),
        '간장' => array(5, 'g', false, '수입'),
        '물엿' => array(1, 'g', false, '국산'),
        '정제수' => array(1, 'g', false, '중국'),
        '식초' => array(1, 'g', false, '중국'),
        '설탕' => array(1, 'g', false, '중국'),
        'L-글루탐산나트륨' => array(1, 'g', false, '수입'),
        '소브산칼륨' => array(1, 'g', false, '수입'),
        '구연산' => array(1, 'g', false, '수입'),
    ),
    '오징어젓갈' => array( // 2019-10-21
        '_total' => array(150, 'g', false, ''),
        '_expired' => array(7, 'days', false, ''),

        '오징어' => array(100, 'g', false, '중국'),
        '참기름' => array(1, 'g', false, '국산'),
        '깨' => array(1, 'g', false, '국산'),
        '물엿' => array(1, 'g', false, '중국'),
        '마늘' => array(1, 'g', false, '중국'),
        '고춧가루' => array(1, 'g', false, '중국'),
        '설탕' => array(1, 'g', false, '중국'),
        '소금' => array(1, 'g', false, '중국'),
        '멸치액젓' => array(1, 'g', false, '수입'),
    ),
    '낙지젓갈' => array( // 2019-10-21
        '_total' => array(150, 'g', false, ''),
        '_expired' => array(7, 'days', false, ''),

        '낙지' => array(100, 'g', false, '중국'),
        '참기름' => array(1, 'g', false, '국산'),
        '깨' => array(1, 'g', false, '국산'),
        '물엿' => array(1, 'g', false, '중국'),
        '마늘' => array(1, 'g', false, '중국'),
        '고춧가루' => array(1, 'g', false, '중국'),
        '멸치액젓' => array(1, 'g', false, '수입'),
        'L-글루탐산나트륨' => array(1, 'g', false, '수입'),
    ),

    // 부침
    '계란말이' => array(
        '_total' => array(200, 'g', false, ''),
        '_expired' => array(4, 'days', false, ''),
        '_regular' => array(2, 3200, 1),

        '계란' => array(4, '개', true, '국산'),
        '맛술' => array(8, 'g', false, '국산'),
        '소금' => array(1.6, 'g', false, '국산'),
        '모듬야채' => array(20, 'g', true, '국산'),
        '맛기름' => array(4, 'g', false, '국산'),
        '깨' => array(1, 'g', false, '국산'),
    ),

    // 고기
    '버터바싹불고기' => array( // 150g 2019-10-17
        '_total' => array(150, 'g', false, ''),
        '_expired' => array(4, 'days', false, ''),
        '_special' => 1,

        '소고기(불고기)' => array(230, 'g', true, '호주'),
        '간장볶음소스' => array(60, 'g', false, ''),
        '간장조림소스' => array(10, 'g', false, ''),
        '버터' => array(8, 'g', false, '국산'),
        '깨' => array(1, 'g', false, '국산'),
        '참기름' => array(2, 'g', false, '국산'),
    ),
    '소불고기' => array( // 150g 2019-10-17
        '_total' => array(150, 'g', false, ''),
        '_expired' => array(4, 'days', false, ''),
        '_special' => 1,

        '소고기(불고기)' => array(200, 'g', true, '호주'),
        '모듬야채' => array(50, 'g', true, '국산'),
        '간장볶음소스' => array(60, 'g', false, ''),
        '간장조림소스' => array(20, 'g', false, ''),
        '깨' => array(1, 'g', false, '국산'),
        '참기름' => array(2, 'g', false, '국산'),
    ),
    '매콤돼지불고기' => array( // 180g 2019-10-12
        '_total' => array(180, 'g', false, ''),
        '_expired' => array(4, 'days', false, ''),
        '_special' => 1,

        '돼지고기(불고기)' => array(180, 'g', true, '국산'),
        '모듬야채' => array(50, 'g', true, '국산'),
        '간장볶음소스' => array(10, 'g', false, ''),
        '고추장볶음소스' => array(80, 'g', false, ''),
        '깨' => array(1, 'g', false, '국산'),
        '참기름' => array(2, 'g', false, '국산'),
    ),
    '매콤닭갈비' => array( // 200g 2020-03-02
        '_total' => array(200, 'g', false, ''),
        '_expired' => array(4, 'days', false, ''),
        '_special' => 1,

        '닭다리살' => array(200, 'g', true, '브라질'),
        '모듬야채' => array(50, 'g', true, '국산'),
        '고추장볶음소스' => array(80, 'g', false, ''),
        '간장볶음소스' => array(10, 'g', false, ''),
        '깻잎' => array(10, 'g', true, '국산'),
        '고구마' => array(10, 'g', true, '국산'),
        '깨' => array(1, 'g', false, '국산'),
        '참기름' => array(2, 'g', false, '국산'),
    ),


    // 국
    '소고기미역국' => array(
        '_total' => array(700, 'g', false, ''),
        '_expired' => array(4, 'days', false, ''),
        '_soup' => 1,

        '소고기(국거리)' => array(50, 'g', true, '호주'),
        '참기름' => array(5, 'g', false, '국산'),
        '미역' => array(15, 'g', true, '국산'),
        '물' => array(480, 'g', false, ''),
        '국간장' => array(25, 'g', false, '국산'),
        '멸치액젓' => array(5, 'g', false, '국산'),
        '소금' => array(1, 'g', false, '국산'),
    ),
    '근대된장국' => array(
        '_total' => array(700, 'g', false, ''),
        '_expired' => array(7, 'days', false, ''),
        '_soup' => 1,

        '멸치육수' => array(580, 'g', false, '국산'),
        '된장' => array(25, 'g', false, '국산'),
        '고추장' => array(11, 'g', false, '국산'),
        '근대' => array(140, 'g', true, '국산'),
        '양파' => array(30, 'g', false, '국산'),
        '마늘' => array(9, 'g', false, '국산'),
        '대파' => array(7, 'g', false, '국산'),
    ),
    '황태국' => array(
        '_total' => array(700, 'g', false, ''),
        '_expired' => array(7, 'days', false, ''),
        '_soup' => 1,

        '황태' => array(20, 'g', true, '러시아'),
        '무' => array(2, 'g', true, '국산'),
        '계란' => array(1, '개', true, '국산'),
        '파' => array(2, 'g', true, '국산'),
        '마늘' => array(2, 'g', true, '국산'),
        '들기름' => array(2, 'g', true, '국산'),
        '국간장' => array(2, 'g', true, '국산'),
        '멸치액젓' => array(2, 'g', true, '국산'),
    ),

    // 부재료
    '모듬야채' => array( // 1g 기준 비율
        '당근' => array(0.4, 'g', false, '국산'),
        '양파' => array(0.4, 'g', false, '국산'),
        '쪽파' => array(0.2, 'g', false, '국산'),
    ),
    '모듬견과류' => array( // 1g 기준 비율
        '호두' => array(0.34, 'g', false, '미국'),
        '호박씨' => array(0.33, 'g', false, '중국'),
        '해바라기씨' => array(0.33, 'g', false, '중국'),
    ),

    // 소스류
    '간장볶음소스' => array( // 1g 기준 비율
        '맛술' => array(0.21, 'g', false, '국산'),
        '마늘' => array(0.20, 'g', false, '국산'),
        '맛간장' => array(0.3, 'g', false, '국산'),
        '노두유' => array(0.02, 'g', false, '홍콩'),
        '굴소스' => array(0.04, 'g', false, '홍콩'),
        '물엿' => array(0.15, 'g', false, '국산'),
        '매실청' => array(0.06, 'g', false, '국산'),
        '후추' => array(0.01, 'g', false, '국산'),
        '생강' => array(0.01, 'g', false, '국산'),
    ),
    '고추장볶음소스' => array( // 1g 기준 비율
        '맛간장' => array(0.26, 'g', false, '국산'),
        '맛술' => array(0.12, 'g', false, '국산'),
        '매실청' => array(0.06, 'g', false, '국산'),
        '물엿' => array(0.2, 'g', false, '국산'),
        '마늘' => array(0.06, 'g', false, '국산'),
        '고추장' => array(0.14, 'g', false, '국산'),
        '고춧가루' => array(0.08, 'g', false, '국산'),
        '두반장' => array(0.03, 'g', false, '홍콩'),
        '굴소스' => array(0.03, 'g', false, '홍콩'),
        '후추' => array(0.01, 'g', false, '국산'),
        '생강' => array(0.01, 'g', false, '국산'),
    ),
    '간장조림소스' => array( // 1g 기준 비율
        '물' => array(0.29, 'g', false, ''),
        '맛간장' => array(0.2, 'g', false, '국산'),
        '간장' => array(0.08, 'g', false, '국산'),
        '물엿' => array(0.14, 'g', false, '국산'),
        '맛술' => array(0.10, 'g', false, '국산'),
        '설탕' => array(0.04, 'g', false, '국산'),
        '노두유' => array(0.02, 'g', false, '홍콩'),
        '굴소스' => array(0.02, 'g', false, '홍콩'),
        '매실청' => array(0.04, 'g', false, '국산'),
        '맛기름' => array(0.05, 'g', false, '국산'),
        '생강' => array(0.01, 'g', false, '국산'),
    ),
    '무침소스' => array( // 1g 기준 비율
        '맛간장' => array(0.25, 'g', false, '국산'),
        '마늘' => array(0.15, 'g', false, '국산'),
        '소금' => array(0.15, 'g', false, '국산'),
        '깨' => array(0.3, 'g', false, '국산'),
        '참기름' => array(0.15, 'g', false, '국산'),
    ),
    /*'맛간장' => array(
        '양파' => array(1, 'g', false, '국산'),
        '표고' => array(1, 'g', false, '국산'),
        '배' => array(1, 'g', false, '국산'),
        '사과' => array(1, 'g', false, '국산'),
        '생강' => array(1, 'g', false, '국산'),
        '마늘' => array(1, 'g', false, '국산'),
        '맛술' => array(1, 'g', false, '국산'),
        '간장' => array(1, 'g', false, '국산'),
        '후추' => array(1, 'g', false, '국산'),
        '설탕' => array(1, 'g', false, '국산'),
        '디포리' => array(1, 'g', false, '국산'),
        '가다랑어포' => array(1, 'g', false, '필리핀'),
    ),*/
);